### ISSUE TITLE
Incorrect Allproc offset iPhone 5

### ISSUE THREAD

**Issue by Cryptiiiic** [jndok/OF32#2]
I ran the tool on an iPhone 5,1 and 5,2 and the allproc resulted in 0x7ffff00c for both kernels. This may happen on other devices, not entirely sure.

**Comment by jndok** [comment]
Version?

**Comment by stek29** [comment]
Can you upload your kcache?

**Comment by Cryptiiiic** [comment]
@jndok 9.3.3 @stek29 [https://www.dropbox.com/s/wh17xba6tyog3tj/iphone5_1_ios_933.dec?dl=0](url)
and [https://www.dropbox.com/s/tzwbk7cqjxns5vt/iphone5_2_ios_933.dec?dl=0](url)

**Comment by stek29** [comment]
@jndok You could try to adopt ianbeer's method with "pgrp dead..." string. I've done that in github.com/stek29/awful-offset-finder, but it could be a bit better (ie don't imply that allproc references would be BEFORE `bx _panic`)

**Comment by stek29** [comment]
Honestly I don't want to port my allproc because it's awful and makes bad assumptions because of my laziness, but seems to work for these kernelcaches.
I didn't quite understand @jndok's method either to help to debug it.

So I'd suggest just to use awful-offset-finder in cases when of32 fails for allproc, but only when it fails.
Porting effort would be a bit higher -- for example, there's no way to find signature not in `__text`.

**Comment by jndok** [comment]
`allproc` is a bit trickier to find, I tried to improvise a new method but it doesn't seem to work on older kernelcaches. A more proper way would be using the method described by Ian Beer [here](https://bugs.chromium.org/p/project-zero/issues/detail?id=965), which is what @stek29 is using.

I can implement it and will do it as soon as I can, the reason I used my current method was out of pure of laziness :P
